version: "3.7"

services:
  app:
    build: .
    container_name: cashback_system_app
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://mongo-db/cashback-system
      - PORT=3001
      - IP=0.0.0.0
      - JWT_SECRET=qIlXTHBzNMRkVrqGfXWNXI7xPtRBrDDH

  mongo-db:
    image: bitnami/mongodb:4.2.6-debian-10-r34
    container_name: mongo-db
    restart: always
