version: 2.1

orbs:
  node: circleci/node@2.1

jobs:
  lint:
    executor:
      name: node/default
      tag: "14.2"
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  build:
    steps:
      - run: npm run webpack-build

  build:
    steps:
      - run: npm test

workflows:
  lint-build-test:
    jobs:
      - lint
      - build:
        requires:
          - lint
      - test:
        requires:
          - build
