version: 2.1

orbs:
  node: circleci/node@2.1

jobs:
  lint-build-test:
    executor:
      name: node/default
      tag: "14.2"
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run webpack-build
      - run: npm test

workflows:
  lint-build-test:
    jobs:
      - lint-build-test
