version: 2.1

orbs:
  node: circleci/node@2.1

jobs:
  lint-build:
    executor:
      name: node/default
      tag: "14.2.0-alpine3.11"
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run webpack-build

workflows:
  lint-build:
    jobs:
      - lint-build
